openapi: 3.2.0
info:
  title: CoreStack External Tagging Governance Definition Versions API
  version: 1.0.0
  termsOfService: http://corestack.io/
  license:
    name: CoreStack Inc License
    url: http://corestack.io/licenses/LICENSE-2.0.html
  description: Manage Tagging Governance Versions
servers:
- url: /
tags:
- name: TaggingGovernanceDefinitionVersions
  description: Manage Tagging Governance Versions
paths:
  /v1/tag_baseline_version/batch:
    post:
      responses:
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelError'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelError'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelError'
        '200':
          description: Fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TagBaselineDefinitionVersion'
      summary: Get Dashboard Versions
      description: Batch Tag Baseline versions
      operationId: batch@@@7
      security:
      - auth_token: []
      tags:
      - TaggingGovernanceDefinitionVersions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecordIdentityBatchRequest'
        required: true
  /v1/tag_baseline_version/create:
    post:
      responses:
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelError'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelError'
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagBaselineDefinitionVersion'
      summary: Create new Tag Baseline Definition Version
      description: Create a Tag Baseline Definition Version. This will create and link a new version to the given definition id.
      operationId: create@@@8
      security:
      - auth_token: []
      tags:
      - TaggingGovernanceDefinitionVersions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagBaselineDefinitionVersion'
        required: true
  /v1/tag_baseline_version/item/{version_id}:
    get:
      responses:
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelError'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelError'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelError'
        '200':
          description: Fetched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagBaselineDefinitionVersion'
      summary: Get Tag Baseline Definition Version
      description: Get a Tag Baseline Definition Version by id.
      operationId: get@@@7
      parameters:
      - name: version_id
        in: path
        required: true
        description: ID of Tag Baseline Definition Version.
        schema:
          type: string
      security:
      - auth_token: []
      tags:
      - TaggingGovernanceDefinitionVersions
  /v1/tag_baseline_version/item/{version_id}/make-head:
    get:
      responses:
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelError'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelError'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelError'
        '200':
          description: Fetched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagBaselineDefinitionVersion'
      summary: Make Tag Baseline Definition Version the Head version
      description: Mark this version as the 'head' version.
      operationId: make-head@@@3
      parameters:
      - name: version_id
        in: path
        required: true
        description: ID of Tag Baseline Definition Version.
        schema:
          type: string
      security:
      - auth_token: []
      tags:
      - TaggingGovernanceDefinitionVersions
  /v1/tag_baseline_version/item/{version_id}/make-release:
    get:
      responses:
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelError'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelError'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelError'
        '200':
          description: Fetched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagBaselineDefinitionVersion'
      summary: Make Tag Baseline Definition Version the Release version
      description: Mark this version as the release version. The release version will be used for posture generation
      operationId: make-release@@@3
      parameters:
      - name: version_id
        in: path
        required: true
        description: ID of Tag Baseline Definition Version.
        schema:
          type: string
      security:
      - auth_token: []
      tags:
      - TaggingGovernanceDefinitionVersions
  /v1/tag_baseline_version/parseImport:
    post:
      responses:
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelError'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelError'
        '200':
          description: Parsed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagBaselineConfiguration'
      summary: Parse Tag Baseline Definition Version
      description: Parse and validate a raw json string to be used for importing a Tag Baseline Definition Version
      operationId: parse-import@@@3
      security:
      - auth_token: []
      tags:
      - TaggingGovernanceDefinitionVersions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RawImport'
        required: true
components:
  schemas:
    TagBaselineDefinitionVersion:
      allOf:
      - $ref: '#/components/schemas/BaseDefinitionVersion'
      - properties:
          details:
            description: Details of the version
            $ref: '#/components/schemas/TagBaselineConfiguration'
        type: object
    BaseDefinitionVersion:
      properties:
        sysId:
          type: string
          description: Identifier of the version
        createdOn:
          type: string
          format: date-time
          description: Version created on
        updatedOn:
          type: string
          format: date-time
          description: Version  updated on
        version:
          type: integer
          default: Sequence number of the version
        definition:
          description: Reference to the definition
          $ref: '#/components/schemas/RecordIdentity'
        predecessor:
          description: Reference to the previous version
          $ref: '#/components/schemas/RecordIdentity'
      type: object
    TagBaselineRule:
      required:
      - __type
      properties:
        category:
          type: array
          description: Categories for this tag
          items:
            type: string
      discriminator:
        propertyName: __type
      type: object
      x-cs-subtypes:
      - subtype_model: TagBaselineRuleAllowedValues
        subtype_name: TagBaselineRuleAllowedValues
      - subtype_model: TagBaselineRuleRegex
        subtype_name: TagBaselineRuleRegex
      - subtype_model: TagBaselineRuleCondition
        subtype_name: TagBaselineRuleCondition
    RawImport:
      properties:
        contentsAsJSON:
          type: string
      type: object
    ModelError:
      required:
      - message
      properties:
        message:
          type: string
          description: Error response message.
      type: object
    RecordIdentityBatchRequest:
      properties:
        ids:
          type: array
          items:
            $ref: '#/components/schemas/RecordIdentity'
      type: object
    RecordIdentity:
      properties:
        sysId:
          type: string
          description: Unique Identifier of the tracked item
        lastUpdate:
          type: string
          format: date-time
          description: Last update of the tracked item
        table:
          type: string
          description: Context of the tracked item
      type: object
    TagBaselineConfiguration:
      required:
      - tags
      properties:
        tags:
          type: object
          description: Tag rules in this baseline
          additionalProperties:
            $ref: '#/components/schemas/TagBaselineRule'
      type: object
  securitySchemes:
    auth_token:
      type: apiKey
      in: header
      name: X-Auth-Token
